### ISSUE TITLE
Chromium Memory leak leading to System Out of Memory (linux docker)

### ISSUE THREAD

**Issue by mik0git** [cestef/webscraper-exporter#4]
Hi, 

I have deployed webscraper-exporter on a Infomaniak Public Cloud instance with basic check very 3min but after a couple of cycles I will get a OOM killing chromium even with a 4GB RAM system. 
Do you have known issue with memory management ? Any chance to mitigate this issue by killing Chromium between every cycle ? 

regards,

Nicolas

**Comment by cestef** [comment]
Sorry about the late response, this should have been fixed in the latest version (`1.2.10`). Feel free to reopen if there's any further issue
